/**
 * The single hand-maintained Help corpus.
 *
 * Consolidated from the two former corpora:
 *  - `desktop/src/lib/help.ts` (`grokptah.help.v1`, capability-aware, uncited)
 *  - `desktop/src/lib/helpCenter.ts` (`product-corpus-v1`, source-cited)
 *
 * Both are now generated projections of this data (see `projections.ts`).
 * Every article carries at least one source anchor. Capability metadata from
 * the former entry corpus is folded onto the article that replaced it via
 * `legacyEntryId`, so no content and no contract was dropped in the merge.
 */
import type { HelpArticleSeed, HelpSourceAnchor } from "./types";

/**
 * Every citable source, keyed by a stable citation id.
 *
 * Ids are unique per `path#heading`. The former corpus reused
 * `product.readme`, `provider.profiles`, and `computer-use.threat-model`
 * across two different headings each, so a citation could not identify which
 * section backed a claim. Those are split here.
 */
export const HELP_SOURCE_REGISTRY: Readonly<Record<string, HelpSourceAnchor>> = Object.freeze({
  "product.readme.quick-start": { id: "product.readme.quick-start", path: "README.md", heading: "Quick start" },
  "product.readme.features": { id: "product.readme.features", path: "README.md", heading: "Features (desktop)" },
  "provider.profiles": { id: "provider.profiles", path: "docs/PROVIDER_PROFILES.md", heading: "Provider profiles" },
  "provider.profiles.qualify": { id: "provider.profiles.qualify", path: "docs/PROVIDER_PROFILES.md", heading: "Qualify a model" },
  "provider.boundaries": { id: "provider.boundaries", path: "docs/PROVIDER_PRODUCT_BOUNDARIES.md", heading: "Grok Build route" },
  "verification.guide": { id: "verification.guide", path: "docs/VERIFICATION.md", heading: "Verification paths" },
  "computer-use.overview": { id: "computer-use.overview", path: "docs/COMPUTER_USE.md", heading: "Safety boundary" },
  "computer-use.trust-boundaries": { id: "computer-use.trust-boundaries", path: "docs/COMPUTER_USE_THREAT_MODEL.md", heading: "Trust boundaries" },
  "computer-use.evidence-matrix": { id: "computer-use.evidence-matrix", path: "docs/COMPUTER_USE_THREAT_MODEL.md", heading: "Evidence matrix" },
  "computer-use.release-blockers": { id: "computer-use.release-blockers", path: "docs/COMPUTER_USE_THREAT_MODEL.md", heading: "Release blockers still open" },
  "durable.runs": { id: "durable.runs", path: "docs/DURABLE_RUNS.md", heading: "Lifecycle" },
  "durable.queue": { id: "durable.queue", path: "docs/MCP_CONTROL_COORDINATOR.md", heading: "Queue" },
  "review.protocol": { id: "review.protocol", path: "docs/MCP_CONTROL_COORDINATOR.md", heading: "Evidence-backed handoff" },
  "mcp.coordinator": { id: "mcp.coordinator", path: "docs/MCP_CONTROL_COORDINATOR.md", heading: "Cross-product capability discovery" },
  "embedding.war-room": { id: "embedding.war-room", path: "docs/EMBEDDING.md", heading: "Browser / War Room example" },
  "embedding.external-workers": { id: "embedding.external-workers", path: "docs/EMBEDDING.md", heading: "External cloud workers" },
  "embedding.headless-primitives": { id: "embedding.headless-primitives", path: "docs/EMBEDDING.md", heading: "Headless UI primitives" },
  "cursor.cloud.integration": { id: "cursor.cloud.integration", path: "docs/CURSOR_CLOUD_INTEGRATION.md", heading: "GrokPtah architecture" },
  "sdk.contract-layers": { id: "sdk.contract-layers", path: "docs/ADR-003-cross-product-capability-surface.md", heading: "Public contract layers" },
  "agents.persistent-lifecycle": { id: "agents.persistent-lifecycle", path: "docs/PERSISTENT_AGENT_PROTOCOL.md", heading: "Lifecycle rules" },
  "agents.persistent-boundary": { id: "agents.persistent-boundary", path: "docs/PERSISTENT_AGENT_PROTOCOL.md", heading: "Boundary" },
  "broker.approval-promotion": { id: "broker.approval-promotion", path: "docs/WEB_BROKER_PROTOCOL.md", heading: "Approval, promotion, and Computer Use" },
});

export const HELP_ARTICLE_SEEDS: readonly HelpArticleSeed[] = Object.freeze([
  {
    id: "getting-started.sessions",
    title: "Sessions, builds, and chats",
    topic: "getting-started",
    summary: "Keep coding builds and ordinary chats separate while working in parallel.",
    body:
      "Builds are the tool-enabled workspace for repository work. Chats are separate conversations for planning or discussion. Use the Builds and Chats tabs to switch modes, and keep multiple lanes open when you need parallel work.",
    aliases: ["coding lane", "conversation", "parallel agents", "new build", "new chat"],
    keywords: ["session", "build", "chat", "lane", "workspace"],
    sourceIds: ["product.readme.quick-start"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["session.observe"],
    localizations: [
      { locale: "es", title: "Sesiones, compilaciones y chats", summary: "Mantén separadas las compilaciones de código y los chats normales mientras trabajas en paralelo.", keywords: ["sesión", "compilación", "chat", "carril", "espacio de trabajo", "paralelo"] },
      { locale: "fr", title: "Sessions, builds et discussions", summary: "Gardez les builds de code et les discussions ordinaires séparés tout en travaillant en parallèle.", keywords: ["session", "build", "discussion", "espace de travail", "parallèle"] },
    ],
  },
  {
    id: "getting-started.search",
    title: "Find an earlier run",
    topic: "getting-started",
    summary: "Search titles, messages, tags, and folders across your saved sessions.",
    body:
      "Open Search from the Lanes sidebar. Hybrid search combines exact text with meaning-based ranking when the semantic index is available; Keyword mode is authoritative for commands and identifiers. Archived sessions can be included explicitly.",
    aliases: ["search history", "find conversation", "look up a build", "semantic search", "search old work"],
    keywords: ["search", "archive", "hybrid", "keyword", "semantic", "session"],
    sourceIds: ["product.readme.features"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["session.observe"],
    localizations: [
      { locale: "es", title: "Encontrar una ejecución anterior", summary: "Busca títulos, mensajes, etiquetas y carpetas en tus sesiones guardadas.", keywords: ["buscar", "búsqueda", "historial", "archivado", "encontrar", "anterior"] },
      { locale: "fr", title: "Retrouver une exécution précédente", summary: "Recherchez les titres, messages, étiquettes et dossiers dans vos sessions enregistrées.", keywords: ["rechercher", "recherche", "historique", "archivé", "trouver"] },
    ],
  },
  {
    id: "getting-started.accessibility",
    title: "Work quickly with keyboard and screen reader",
    topic: "getting-started",
    summary: "Power-user speed and accessibility are designed together: named landmarks, predictable focus, and visible state.",
    body:
      "A consumer of the headless primitives owns its own rendering, focus management, and approval presentation, so accessible structure has to come from the shared result and citation metadata rather than desktop styling. Running state, permission requests, stale observations, and recovery actions must stay announced and visible. Reduced motion and large text settings preserve the same information hierarchy instead of hiding status.",
    aliases: ["keyboard navigation", "screen reader", "large text", "focus order", "high contrast", "reduced motion"],
    keywords: ["accessibility", "keyboard", "screen reader", "focus", "contrast", "landmark", "announce"],
    sourceIds: ["embedding.headless-primitives"],
    audience: ["everyone", "power_user"],
    access: "public",
    capabilityIds: [],
    legacyEntryId: "power-user-accessibility",
    localizations: [],
  },
  {
    id: "providers.gateway",
    title: "Provider routes and gateway policy",
    topic: "providers",
    summary: "Choose an explicit provider route and see what is actually qualified.",
    body:
      "Provider profiles describe the selected model, gateway, and capability evidence. A configured route is not the same as a live certification, and GrokPtah does not synchronize a provider account balance. Readiness and quota observability are shown separately so evidence is not mistaken for a claim.",
    aliases: ["company gateway", "restricted model", "weaker model", "weak model", "quota", "provider settings"],
    keywords: ["provider", "company", "gateway", "route", "model", "quota", "certification", "readiness"],
    sourceIds: ["provider.profiles"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["run.execute"],
    localizations: [
      { locale: "es", title: "Rutas de proveedor y política de pasarela", summary: "Elige una ruta de proveedor explícita y comprueba qué está realmente cualificado.", keywords: ["proveedor", "pasarela", "ruta", "modelo", "cuota", "certificación"] },
      { locale: "de", title: "Anbieterrouten und Gateway-Richtlinie", summary: "Wählen Sie eine explizite Anbieterroute und sehen Sie, was tatsächlich qualifiziert ist.", keywords: ["anbieter", "gateway", "route", "modell", "kontingent", "zertifizierung"] },
    ],
  },
  {
    id: "providers.live-gateway-evidence",
    title: "Live gateway evidence and quota",
    topic: "providers",
    summary: "Know when a run used a real company gateway and what it can prove.",
    body:
      "A live gateway campaign must name the fixed route, tenant, model, authorization boundary, and receipt evidence. Local scripted-provider tests validate lifecycle behavior without spending external quota; they do not certify gateway routing, quota exhaustion, latency, or model quality.",
    aliases: ["real gateway", "live provider", "grok build quota", "quota receipt", "company review lane"],
    keywords: ["live", "gateway", "quota", "receipt", "tenant", "authorization", "latency"],
    sourceIds: ["provider.profiles.qualify", "verification.guide"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["run.execute", "run.review"],
    localizations: [],
  },
  {
    id: "providers.grok-build-boundary",
    title: "Grok Build, Grok Bot, and external tools",
    topic: "providers",
    summary: "Keep the Grok Build route separate from Grok Bot and development-tool usage.",
    body:
      "GrokPtah can use an explicitly configured Grok Build route, but a real quota claim requires a named live campaign and secret-free receipts. The local always-on soak uses a loopback provider and does not contact Grok Build. Grok Bot is a separate product and is not a GrokPtah runtime dependency or manager; Claude Code, Cursor, and user-submitted Grok Build prompts are external development tools, not automatic runtime providers.",
    aliases: ["grok build vs grok bot", "grokbot", "grok bot quota", "which grok", "external coding tools", "cursor grok"],
    keywords: ["grok", "bot", "boundary", "cursor", "claude", "external"],
    sourceIds: ["provider.boundaries", "provider.profiles"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: [],
    localizations: [],
  },
  {
    id: "providers.restricted-gateway-review",
    title: "Review code through a restricted company gateway",
    topic: "providers",
    summary: "Use a weaker approved model and a long-running company route without pretending it is frontier-certified.",
    body:
      "A company gateway can still run a bounded, read-only code review when the route, tenant, model, and authority policy are fixed. GrokPtah should preserve useful partial findings on throttles or timeouts, never silently fall back, and show whether the evidence is a configured route, a live receipt, or only a local test. The review receipt records the exact repository, base and head, gateway route, model, and findings without copying credentials or account balances.",
    aliases: ["weak gateway code review", "restricted AI policy", "long running company agent", "use the model we have", "enterprise review", "restricted gateway"],
    keywords: ["company", "restricted", "review", "read-only", "fallback", "tenant", "authority", "enterprise", "compliance"],
    sourceIds: ["provider.profiles", "verification.guide"],
    audience: ["power_user", "operator"],
    access: "operator",
    capabilityIds: ["run.review"],
    legacyEntryId: "enterprise-gateway-review",
    localizations: [
      { locale: "es", title: "Revisar código a través de una pasarela corporativa restringida", summary: "Usa un modelo aprobado más débil y una ruta corporativa de larga duración sin fingir una certificación de frontera.", keywords: ["revisión", "código", "pasarela", "restringida", "empresa", "corporativa"] },
    ],
  },
  {
    id: "providers.browser-broker",
    title: "Embed GrokPtah in a War Room",
    topic: "providers",
    summary: "Give a browser observe/review powers through a broker without exposing desktop authority.",
    body:
      "A War Room or other browser UI uses the browser-safe broker client with an authenticated session, opaque binding and run IDs, CSRF protection, and idempotency keys. The broker owns provider credentials and re-checks user, team, workspace, capability, and run scope. Browser code must never receive a bearer token, raw path, or native Computer Use authority.",
    aliases: ["ContextDesk integration", "War Room broker", "browser client", "embed GrokPtah", "web UI integration"],
    keywords: ["browser", "broker", "War Room", "embed", "ContextDesk", "opaque", "CSRF", "credential"],
    sourceIds: ["embedding.war-room"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["session.observe", "run.review"],
    localizations: [],
  },
  {
    id: "providers.external-cloud-workers",
    title: "Launch and monitor a cloud coding worker",
    topic: "providers",
    summary: "Spin up an isolated external coding agent and review its bounded evidence through the broker.",
    body:
      "External workers use the provider-neutral GrokPtah contract: pin the exact repository and starting ref, require isolated execution, monitor redacted status and cursor recovery, and collect only bounded relative artifacts. Cursor Cloud and future Claude Code adapters keep credentials server-side. Creating a draft PR never approves or merges changes; review receipts and the existing human promotion gate remain separate.",
    aliases: ["cloud agent", "Cursor Cloud worker", "external coding agent", "spawn remote agent", "agent harness worker"],
    keywords: ["cloud", "worker", "Cursor", "Claude", "external", "isolated", "artifact", "review", "promotion"],
    sourceIds: ["cursor.cloud.integration", "embedding.external-workers"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["run.execute", "run.review"],
    localizations: [],
  },
  {
    id: "providers.sdk-contracts",
    title: "Use GrokPtah from another project",
    topic: "providers",
    summary: "Embed the versioned Rust and TypeScript capability contracts in a desktop app, web broker, or service.",
    body:
      "The agent SDK crate owns versioned, serializable contracts for capability discovery, sessions and durable run state, queue and steer operations with request IDs and compare-and-set versions, review and promotion receipts, provider profile identity, typed event pages and cursors, and redaction categories. It carries no Tauri, keychain, filesystem, or provider SDK dependency, and no execution policy that requires the desktop. The same contract is representable as versioned wire schema so TypeScript and other clients do not reimplement the DTOs independently.",
    aliases: ["embed the SDK", "reuse GrokPtah", "integrate contracts", "client package", "cross-project reuse", "typed client"],
    keywords: ["sdk", "contract", "schema", "client", "integration", "versioned", "capability", "package"],
    sourceIds: ["sdk.contract-layers"],
    audience: ["power_user", "operator"],
    access: "public",
    capabilityIds: ["session.observe", "run.execute", "run.review"],
    legacyEntryId: "capabilities-and-integrations",
    localizations: [],
  },
  {
    id: "computer-use.boundaries",
    title: "Computer Use: consent and boundaries",
    topic: "computer-use",
    summary: "Understand what Computer Use can observe or do, and what it refuses.",
    body:
      "Computer Use is bounded by an explicit target, fresh observation, one-use approval, and a postcondition. Stop and Take over revoke authority. Secure fields, stale observations, focus changes, raw global input, clipboard injection, shell control, and unattended actions fail closed or remain unsupported. Unredacted clipboard, credential, path, and network data are not part of the public contract.",
    aliases: ["computer control", "clicking", "screen access", "safe automation", "mouse and keyboard"],
    keywords: ["computer", "consent", "observation", "approval", "stop", "takeover", "secure", "unsupported"],
    sourceIds: ["computer-use.overview", "computer-use.trust-boundaries"],
    audience: ["everyone", "power_user", "operator"],
    access: "gated",
    capabilityIds: ["computer.observe", "computer.control"],
    legacyEntryId: "computer-use-safety",
    localizations: [
      { locale: "es", title: "Uso del ordenador: consentimiento y límites", summary: "Comprende qué puede observar o hacer el Uso del ordenador y qué rechaza.", keywords: ["ordenador", "consentimiento", "límites", "observación", "aprobación", "pantalla"] },
      { locale: "fr", title: "Computer Use : consentement et limites", summary: "Comprenez ce que Computer Use peut observer ou faire, et ce qu'il refuse.", keywords: ["ordinateur", "consentement", "limites", "observation", "approbation", "écran"] },
    ],
  },
  {
    id: "computer-use.isolated-guest",
    title: "Isolated guest Computer Use",
    topic: "computer-use",
    summary: "Understand the isolated guest boundary without treating source proof as a usable VM.",
    body:
      "An isolated guest is a planned separate visual surface for bounded Computer Use, but it is not qualified for use in this release. The helper and guest image still need review and signing, one agent lease must control a guest at a time, frames must be redacted, and host clipboard, shares, raw global input, and guest networking remain denied. Source-level lease and projection tests do not prove a packaged VM, guest boot, rendered frames, or host input.",
    aliases: ["VM computer use", "virtual machine screen", "sandboxed desktop", "isolated visual", "guest computer", "non disruptive computer use"],
    keywords: ["guest", "VM", "isolated", "helper", "lease", "frame", "redaction", "sandbox"],
    sourceIds: ["computer-use.release-blockers"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["computer.observe"],
    localizations: [],
  },
  {
    id: "computer-use.multi-agent-coordination",
    title: "Coordinate multiple Computer Use agents",
    topic: "computer-use",
    summary: "Keep simultaneous agents from fighting over the same visual surface.",
    body:
      "Computer Use coordination is lease-based: an agent must hold the exact guest/session authority and revision before it can act. A second agent, stale observation, wrong session, Stop, or Take over must be denied without mutation. Separate guests or explicitly disjoint scopes are required for parallel work.",
    aliases: ["two agents one screen", "multiple agents", "agent contention", "share a computer", "coordinate computer agents", "stale visual state"],
    keywords: ["multi-agent", "coordination", "lease", "revision", "stale", "scope", "contention"],
    sourceIds: ["computer-use.evidence-matrix"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["computer.observe", "computer.control"],
    localizations: [],
  },
  {
    id: "computer-use.consent",
    title: "Approve a Computer Use action",
    topic: "computer-use",
    summary: "Understand the one-use consent, postcondition, and takeover controls around visual actions.",
    body:
      "Observation and control are separate capabilities. Before a semantic action, verify the fresh target, scope, lease, and postcondition; approve only the action class you intend. Stop, Take over, focus changes, outdated visual state, secure fields, and cleanup uncertainty revoke authority or fail closed. A focused app window is not proof that an isolated target is safe.",
    aliases: ["computer approval", "take over agent", "visual action consent", "postcondition", "semantic click safety"],
    keywords: ["approve", "Computer", "consent", "lease", "postcondition", "takeover", "cleanup"],
    sourceIds: ["computer-use.overview"],
    audience: ["everyone", "power_user", "operator"],
    access: "gated",
    capabilityIds: ["computer.control"],
    localizations: [],
  },
  {
    id: "operations.evidence",
    title: "Read progress and evidence correctly",
    topic: "operations",
    summary: "Separate deterministic tests, live-provider evidence, hardware proof, and soak reports.",
    body:
      "A passing unit test proves an in-tree behavior on a named revision. It does not prove a live provider campaign, a packaged macOS identity, a multi-day operational soak, or a VM guest. Always read the exact revision, evidence kind, remaining gate, and whether the result is candidate-only.",
    aliases: ["is this certified", "what does pass mean", "qualification", "proof", "release gate"],
    keywords: ["evidence", "test", "hardware", "live", "soak", "certified", "qualification", "release"],
    sourceIds: ["verification.guide"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["run.review"],
    localizations: [],
  },
  {
    id: "operations.always-on-soak",
    title: "Always-on operational soak",
    topic: "operations",
    summary: "Interpret the long-running worker campaign without confusing it with live-provider certification.",
    body:
      "The always-on soak runs the real local service process for a measured duration against a controlled loopback provider. It checks leases, restarts, reconnects, duplicate prevention, credential rotation, resource ceilings, cleanup, and secret-free evidence. A separate live-gateway campaign is required for external provider behavior.",
    aliases: ["72 hour test", "multi-day soak", "persistent workers", "durable agents", "endurance run"],
    keywords: ["soak", "always-on", "worker", "restart", "reconnect", "lease", "duplicate", "cleanup"],
    sourceIds: ["verification.guide"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["run.execute"],
    localizations: [],
  },
  {
    id: "operations.help-assistant",
    title: "Search Help and ask for guidance safely",
    topic: "operations",
    summary: "Search is local and deterministic; an optional assistant may explain cited results but cannot grant authority.",
    body:
      "Help search is offline-first and works with no provider configured. Use natural language, capability names, or tags such as 'stale frame', 'restricted gateway', or 'restart duplicate'. Meaning-based ranking and the optional assistant are separate, explicit actions: the app shows the selected provider, sends only the selected article metadata or cited context, validates article IDs and citations, and labels generated text as a draft rather than product truth. Workspace paths, transcripts, credentials, clipboard data, and actions stay out of the request, and any assistant answer must re-check live capabilities, approvals, leases, and scope before suggesting an action.",
    aliases: ["AI help", "ask product questions", "grounded assistant", "help chatbot", "cited answer", "safe help model", "ask the help assistant"],
    keywords: ["assistant", "help", "citation", "confirmation", "privacy", "offline", "draft", "documentation"],
    sourceIds: ["verification.guide"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: [],
    legacyEntryId: "help-search-and-assistant",
    localizations: [
      { locale: "es", title: "Buscar en la Ayuda y pedir orientación de forma segura", summary: "La búsqueda es local y determinista; un asistente opcional puede explicar resultados citados pero no concede autoridad.", keywords: ["ayuda", "búsqueda", "asistente", "cita", "sin conexión", "documentación"] },
      { locale: "fr", title: "Rechercher dans l'aide et demander conseil en toute sécurité", summary: "La recherche est locale et déterministe ; un assistant optionnel peut expliquer les résultats cités mais n'accorde aucune autorité.", keywords: ["aide", "recherche", "assistant", "citation", "hors ligne", "documentation"] },
    ],
  },
  {
    id: "operations.durable-recovery",
    title: "Recover a durable run safely",
    topic: "operations",
    summary: "Resume from an explicit checkpoint without guessing whether a send happened.",
    body:
      "Durable runs expose a state, cursor, and evidence trail that survive an app restart. A restart is not permission to resend. Reconnect from the advertised cursor, resume only from a durable checkpoint with the same scoped run identity and idempotency key, treat uncertain delivery as unknown, and use an explicit retry or continuation action. Never infer that a linked session or a visible queue means a provider request was sent.",
    aliases: ["restart a run", "recover interrupted agent", "resume after crash", "unknown send", "checkpoint recovery", "restart duplicate"],
    keywords: ["durable", "restart", "recover", "checkpoint", "cursor", "retry", "uncertain", "resume", "replay", "duplicate"],
    sourceIds: ["durable.runs"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["session.observe", "run.execute", "run.review"],
    legacyEntryId: "durable-runs-and-recovery",
    localizations: [
      { locale: "es", title: "Recuperar una ejecución duradera de forma segura", summary: "Reanuda desde un punto de control explícito sin adivinar si se envió una solicitud.", keywords: ["duradera", "recuperar", "reanudar", "reinicio", "punto de control", "duplicado"] },
      { locale: "de", title: "Einen dauerhaften Lauf sicher wiederherstellen", summary: "Setzen Sie an einem expliziten Prüfpunkt fort, ohne zu raten, ob ein Senden stattgefunden hat.", keywords: ["dauerhaft", "wiederherstellen", "fortsetzen", "neustart", "prüfpunkt", "duplikat"] },
    ],
  },
  {
    id: "operations.prompt-queue",
    title: "Queue and steer work without losing scope",
    topic: "operations",
    summary: "Keep future prompts ordered while steering only the active run you intend.",
    body:
      "The prompt queue is scoped to a session and carries revisions so an out-of-order snapshot cannot overwrite a newer queue. Queue and steer are separate bounded operations, not hidden prompt injection. Use a fresh idempotency key for each intent, preserve the run and workspace identity, and reconcile the queue revision before editing or removing an entry. A stale revision or uncertain delivery must fail closed instead of silently targeting another turn; a retry after an uncertain response is allowed only when the durable oracle proves the original request was not accepted.",
    aliases: ["prompt queue", "steer agent", "send next prompt", "queue work", "deferred steering", "cancel queued prompt"],
    keywords: ["queue", "prompt", "steer", "revision", "session", "ordering", "stale", "idempotency", "retry", "cancel"],
    sourceIds: ["durable.queue"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["run.queue", "run.execute"],
    legacyEntryId: "queue-and-steering",
    localizations: [],
  },
  {
    id: "operations.review-receipts",
    title: "Read review receipts and changes",
    topic: "operations",
    summary: "Verify the exact changed files and evidence before approving a run.",
    body:
      "A review receipt binds the changed-file list, bounded diff, fingerprint, tests, and handoff to one run identity. Check the exact workspace and revision, inspect the redacted evidence, and keep approval separate from promotion. A green provider response without a matching receipt is not approval evidence.",
    aliases: ["review changes", "approval receipt", "changed file list", "diff fingerprint", "approve code review"],
    keywords: ["review", "receipt", "changed", "diff", "fingerprint", "approval", "promotion", "handoff"],
    sourceIds: ["review.protocol"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["run.review"],
    localizations: [],
  },
  {
    id: "operations.mcp-coordination",
    title: "Coordinate MCP tools and live events",
    topic: "operations",
    summary: "Use negotiated MCP tools without treating transport reachability as authority.",
    body:
      "MCP coordination negotiates a versioned capability set, session scope, and event cursor. The transport can report a tool, but the desktop authority still applies approvals, leases, workspace fences, and redaction. Reconnect from the advertised cursor and handle recovery notifications instead of replaying an uncertain mutation.",
    aliases: ["MCP tools", "tool coordinator", "live events", "MCP reconnect", "capability negotiation"],
    keywords: ["MCP", "tool", "coordinator", "capability", "cursor", "reconnect", "authority", "event"],
    sourceIds: ["mcp.coordinator"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["session.observe"],
    localizations: [],
  },
  {
    id: "operations.persistent-agents",
    title: "Operate persistent agents",
    topic: "operations",
    summary: "Persistent agents have explicit ownership, bounded rounds, continuation plans, and terminal evidence.",
    body:
      "A persistent agent is identified by an explicit agent id, session, workspace, model, lifecycle state, and latest checkpoint. Opening the store converts queued or running runs to interrupted and marks their bound agents interrupted while retaining the latest verified checkpoint. Resume is manual: the caller supplies a fresh prompt, and the host validates agent, session, workspace, and checkpoint identity before injecting the bounded checkpoint context and linking the new run to its parent. This slice adds no scheduler, unattended auto-resume, headless authority, or auto-promotion.",
    aliases: ["long running agent", "always on agent", "background worker", "supervisor agent", "continuation plan", "resume an agent"],
    keywords: ["agent", "persistent", "checkpoint", "resume", "lifecycle", "continuation", "interrupted", "budget"],
    sourceIds: ["agents.persistent-lifecycle", "agents.persistent-boundary"],
    audience: ["power_user", "operator"],
    access: "gated",
    capabilityIds: ["agent.continuity", "agent.resume"],
    legacyEntryId: "persistent-agents",
    localizations: [],
  },
  {
    id: "operations.approvals",
    title: "Understand approvals and permissions",
    topic: "operations",
    summary: "A visible capability is not automatically executable; mutating and computer actions require their declared gate.",
    body:
      "Approval and promotion are separate endpoints with separate audit records. Review the requested scope, target, risk, and expiry before approving, and deny or pause when the observed target changed. A browser session, a focused tab, or a team role is not a Computer Use grant; control requests must carry the expected run revision and action class, and stale revisions are rejected without mutation. Approval is scoped to the current run and capability and never silently expands to raw input, another workspace, another agent, or a future revision.",
    aliases: ["consent", "human gate", "authorize", "deny a request", "permission scope", "who can approve"],
    keywords: ["permission", "approval", "security", "scope", "authorize", "deny", "risk", "expiry", "revision"],
    sourceIds: ["broker.approval-promotion"],
    audience: ["everyone", "power_user", "operator"],
    access: "public",
    capabilityIds: ["run.execute", "run.promote", "computer.control"],
    legacyEntryId: "approvals-and-permissions",
    localizations: [
      { locale: "es", title: "Comprender las aprobaciones y los permisos", summary: "Una capacidad visible no es automáticamente ejecutable; las acciones mutantes requieren su control declarado.", keywords: ["aprobación", "permiso", "seguridad", "alcance", "autorizar", "denegar"] },
    ],
  },
  {
    id: "operations.promotion-and-discard",
    title: "Promote or discard an isolated review safely",
    topic: "operations",
    summary: "Promotion consumes a short-lived approval bound to exact fingerprints, changed files, and the same run.",
    body:
      "The approve step must display the exact source and final fingerprints and the changed-file list returned by the review, using the same changed-file object shape as the review receipt; a path-only list is not sufficient evidence. Promotion accepts only the matching short-lived approval receipt and a new idempotency key, so stale, expired, mismatched, or replayed approvals deny without mutation. Discard is explicit and must leave an auditable terminal receipt.",
    aliases: ["promote changes", "merge isolated work", "discard a review", "approval expiry", "promotion receipt"],
    keywords: ["promotion", "discard", "review", "fingerprint", "approve", "promote", "receipt", "expiry", "idempotency"],
    sourceIds: ["broker.approval-promotion"],
    audience: ["power_user", "operator"],
    access: "operator",
    capabilityIds: ["run.promote", "run.review"],
    legacyEntryId: "promotion-and-discard",
    localizations: [],
  },
]);
