//! The authored Help corpus: seeds in, digest-bound corpus out.
//!
//! This is the *only* hand-maintained Help content in the tree. The legacy
//! `grokptah.help.v1` entry corpus and the `product-corpus-v1` article corpus
//! were two separately edited sets that answered the same questions
//! differently; both are replaced by what is written here.
//!
//! Every article must cite at least one source that resolves to a real
//! `path#heading` in this repository, and no article may be less restricted
//! than a source it cites — otherwise a public reader would learn that a gated
//! document exists from the citation alone.

use crate::corpus::{ArticleSeed, SourceSeed, Topic, Visibility};

/// Sources are the citation targets. Visibility here is the floor for any
/// article citing them.
pub const SOURCES: &[SourceSeed] = &[
    SourceSeed {
        id: "product.readme.quickstart",
        path: "README.md",
        heading: "Quick start",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "product.readme.features",
        path: "README.md",
        heading: "Features (desktop)",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "provider.profiles",
        path: "docs/PROVIDER_PROFILES.md",
        heading: "Configure a provider",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "provider.qualify",
        path: "docs/PROVIDER_PROFILES.md",
        heading: "Qualify a model",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "provider.boundaries",
        path: "docs/PROVIDER_PRODUCT_BOUNDARIES.md",
        heading: "Grok Build route",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "provider.bot-boundary",
        path: "docs/PROVIDER_PRODUCT_BOUNDARIES.md",
        heading: "Grok Bot boundary",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "computer-use.safety",
        path: "docs/COMPUTER_USE.md",
        heading: "Safety boundary",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "computer-use.non-goals",
        path: "docs/COMPUTER_USE.md",
        heading: "Deliberate non-goals of the current desktop slice",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "computer-use.trust",
        path: "docs/COMPUTER_USE_THREAT_MODEL.md",
        heading: "Trust boundaries",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "computer-use.blockers",
        path: "docs/COMPUTER_USE_THREAT_MODEL.md",
        heading: "Release blockers still open",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "computer-use.evidence",
        path: "docs/COMPUTER_USE_THREAT_MODEL.md",
        heading: "Evidence matrix",
        visibility: Visibility::Operator,
    },
    SourceSeed {
        id: "durable.lifecycle",
        path: "docs/DURABLE_RUNS.md",
        heading: "Lifecycle",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "durable.bounds",
        path: "docs/DURABLE_RUNS.md",
        heading: "Privacy and bounds",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "verification.paths",
        path: "docs/VERIFICATION.md",
        heading: "Supported paths (what CI runs, and what you should run)",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "verification.unsupported",
        path: "docs/VERIFICATION.md",
        heading: "Unsupported: root-wide `cargo test` / `cargo test --workspace [--no-run]`",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "mcp.coordinator",
        path: "docs/MCP_CONTROL_COORDINATOR.md",
        heading: "Launch (desktop / production)",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "mcp.retention",
        path: "docs/MCP_CONTROL_COORDINATOR.md",
        heading: "Durable retention",
        visibility: Visibility::Operator,
    },
    SourceSeed {
        id: "embedding.trust",
        path: "docs/EMBEDDING.md",
        heading: "Choose the trust boundary first",
        visibility: Visibility::Public,
    },
    SourceSeed {
        id: "embedding.broker",
        path: "docs/EMBEDDING.md",
        heading: "Browser / War Room example",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "embedding.workers",
        path: "docs/EMBEDDING.md",
        heading: "External cloud workers",
        visibility: Visibility::Gated,
    },
    SourceSeed {
        id: "embedding.primitives",
        path: "docs/EMBEDDING.md",
        heading: "Headless UI primitives",
        visibility: Visibility::Public,
    },
];

/// Articles. `visibility` is what a principal must clear to be served this at
/// all; `capability_ids` are additionally required.
pub const ARTICLES: &[ArticleSeed] = &[
    ArticleSeed {
        id: "getting-started.sessions",
        title: "Sessions, builds, and chats",
        topic: Topic::GettingStarted,
        summary: "Keep coding builds and ordinary chats separate while working in parallel.",
        body: "Builds are the tool-enabled workspace for repository work. Chats are separate conversations for planning or discussion. Use the Builds and Chats tabs to switch modes, and keep multiple lanes open when you need parallel work. Help is its own surface and does not open a chat on your behalf.",
        aliases: &[
            "coding lane",
            "conversation",
            "parallel agents",
            "new build",
            "new chat",
        ],
        keywords: &["session", "build", "chat", "lane", "workspace"],
        source_ids: &["product.readme.quickstart", "product.readme.features"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "getting-started.search",
        title: "Find an earlier run",
        topic: Topic::GettingStarted,
        summary: "Search titles, messages, tags, and folders across your saved sessions.",
        body: "Open Search from the Lanes sidebar. Hybrid search combines exact text with meaning-based ranking over the offline index; Keyword mode stays authoritative for commands and identifiers. Archived sessions are included only when you ask for them.",
        aliases: &[
            "search history",
            "find conversation",
            "look up a build",
            "semantic search",
            "search old work",
        ],
        keywords: &[
            "search", "archive", "hybrid", "keyword", "semantic", "session",
        ],
        source_ids: &["product.readme.features"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "getting-started.help-center",
        title: "Search Help and read a cited answer",
        topic: Topic::GettingStarted,
        summary: "Help retrieval runs offline; a cited answer is an extra, explicit step.",
        body: "Type a question and Help searches the shipped corpus in your own process, with no network call. Asking for a written answer is a separate action: the host selects the passages, sends one bounded request, and shows the reply only after it has checked every claim against the exact corpus bytes. Claims that cannot be tied to a cited passage are dropped, and an answer with no supported claim is withheld rather than shown as a guess.",
        aliases: &[
            "ai help",
            "ask product questions",
            "grounded assistant",
            "help chatbot",
            "cited answer",
            "how do i",
        ],
        keywords: &[
            "help",
            "citation",
            "offline",
            "assistant",
            "draft",
            "grounded",
            "abstain",
        ],
        source_ids: &["product.readme.features", "embedding.primitives"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "getting-started.accessibility",
        title: "Work quickly with keyboard and screen reader",
        topic: Topic::GettingStarted,
        summary: "Power-user speed and accessibility are designed together: named landmarks, predictable focus, and visible state.",
        body: "Use the Sessions, Tools, Live, and Computer landmarks to move between work areas. Running state, permission requests, stale observations, and recovery actions are announced and stay visible. Reduced motion and large text preserve the same information hierarchy rather than hiding status.",
        aliases: &[
            "keyboard shortcuts",
            "screen reader",
            "accessible",
            "focus order",
            "reduced motion",
        ],
        keywords: &[
            "accessibility",
            "keyboard",
            "focus",
            "contrast",
            "aria",
            "landmark",
        ],
        source_ids: &["embedding.primitives", "product.readme.features"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "providers.routes",
        title: "Provider routes and gateway policy",
        topic: Topic::Providers,
        summary: "Choose an explicit provider route and see what is actually qualified.",
        body: "Provider profiles describe the selected model, gateway, and capability evidence. A configured route is not a live certification, and GrokPtah does not synchronize a provider account balance. Readiness and quota observability are shown separately so evidence is not mistaken for a claim.",
        aliases: &[
            "company gateway",
            "restricted model",
            "weaker model",
            "quota",
            "provider settings",
        ],
        keywords: &[
            "provider",
            "gateway",
            "route",
            "model",
            "quota",
            "readiness",
        ],
        source_ids: &["provider.profiles"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "providers.product-boundary",
        title: "Grok Build, Grok Bot, and external tools",
        topic: Topic::Providers,
        summary: "Keep the Grok Build route separate from Grok Bot and development-tool usage.",
        body: "GrokPtah can use an explicitly configured Grok Build route, but a real quota claim requires a named live campaign and secret-free receipts. The local always-on soak uses a loopback provider and does not contact Grok Build. Grok Bot is a separate product and is not a runtime dependency or manager.",
        aliases: &[
            "grok build vs grok bot",
            "grokbot",
            "which grok",
            "external coding tools",
        ],
        keywords: &["grok", "bot", "boundary", "external", "loopback"],
        source_ids: &["provider.boundaries", "provider.bot-boundary"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "providers.restricted-gateway-review",
        title: "Review code through a restricted company gateway",
        topic: Topic::Providers,
        summary: "Use a permitted gateway for code review while preserving evidence and policy boundaries.",
        body: "A company gateway can still run a bounded, read-only code review when the route, tenant, model, and authority policy are fixed. Preserve useful partial findings on throttles or timeouts, never silently fall back, and show whether the evidence is a configured route, a live receipt, or only a local test.",
        aliases: &[
            "weak gateway code review",
            "restricted AI policy",
            "enterprise review",
            "use the model we have",
        ],
        keywords: &[
            "company",
            "restricted",
            "review",
            "read-only",
            "fallback",
            "tenant",
        ],
        source_ids: &["provider.profiles", "provider.qualify"],
        visibility: Visibility::Gated,
        capability_ids: &["run.review"],
    },
    ArticleSeed {
        id: "providers.embedding",
        title: "Use GrokPtah from another project",
        topic: Topic::Providers,
        summary: "Embed the versioned contracts in a desktop app, web broker, or service.",
        body: "Start by choosing the trust boundary, then take the transport-neutral clients that match it. Consumers discover capabilities, scope every run, and preserve the same approval, replay, and redaction rules. The published Help package ships offline retrieval, projections, validation, and rendering — never authority constructors, route selection, transport, or private corpus.",
        aliases: &[
            "embed grokptah",
            "sdk",
            "integration",
            "published package",
            "reuse",
        ],
        keywords: &["embed", "sdk", "package", "broker", "contract", "boundary"],
        source_ids: &["embedding.trust", "embedding.primitives"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "providers.browser-broker",
        title: "Give a browser observe and review powers",
        topic: Topic::Providers,
        summary: "A browser UI reaches GrokPtah through a broker that keeps authority server-side.",
        body: "A browser client uses an authenticated session, opaque binding and run identifiers, CSRF protection, and idempotency keys. The broker owns provider credentials and re-checks user, team, workspace, capability, and run scope on every call. Browser code never receives a bearer token, a raw path, or native Computer Use authority.",
        aliases: &["war room", "browser client", "web ui integration", "broker"],
        keywords: &["browser", "broker", "opaque", "csrf", "credential", "scope"],
        source_ids: &["embedding.broker", "embedding.trust"],
        visibility: Visibility::Gated,
        capability_ids: &["session.observe"],
    },
    ArticleSeed {
        id: "providers.external-workers",
        title: "Launch and monitor a cloud coding worker",
        topic: Topic::Providers,
        summary: "Spin up an isolated external coding agent and review its bounded evidence.",
        body: "External workers use the provider-neutral contract: pin the exact repository and starting ref, require isolated execution, monitor redacted status and cursor recovery, and collect only bounded relative artifacts. Creating a draft pull request never approves or merges changes; review receipts and the human promotion gate stay separate.",
        aliases: &[
            "cloud agent",
            "external coding agent",
            "remote worker",
            "agent harness",
        ],
        keywords: &[
            "cloud",
            "worker",
            "external",
            "isolated",
            "artifact",
            "promotion",
        ],
        source_ids: &["embedding.workers"],
        visibility: Visibility::Gated,
        capability_ids: &["run.execute"],
    },
    ArticleSeed {
        id: "computer-use.boundaries",
        title: "Computer Use: consent and boundaries",
        topic: Topic::ComputerUse,
        summary: "Understand what Computer Use can observe or do, and what it refuses.",
        body: "Computer Use is bounded by an explicit target, a fresh observation, a one-use approval, and a postcondition. Stop and Take over revoke authority. Secure fields, stale observations, focus changes, raw global input, clipboard injection, shell control, and unattended actions fail closed or remain unsupported.",
        aliases: &[
            "computer control",
            "clicking",
            "screen access",
            "safe automation",
            "mouse and keyboard",
        ],
        keywords: &[
            "computer",
            "consent",
            "observation",
            "approval",
            "stop",
            "takeover",
        ],
        source_ids: &["computer-use.safety", "computer-use.non-goals"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "computer-use.approval",
        title: "Approve a Computer Use action",
        topic: Topic::ComputerUse,
        summary: "Understand the one-use consent, postcondition, and takeover controls.",
        body: "Observation and control are separate capabilities. Before a semantic action, verify the fresh target, scope, lease, and postcondition, and approve only the action class you intend. Outdated visual state, secure fields, focus changes, and cleanup uncertainty revoke authority or fail closed. A focused window is not proof that a target is safe.",
        aliases: &[
            "computer approval",
            "take over agent",
            "visual action consent",
            "postcondition",
        ],
        keywords: &[
            "approve",
            "consent",
            "lease",
            "postcondition",
            "takeover",
            "cleanup",
        ],
        source_ids: &["computer-use.safety", "computer-use.trust"],
        visibility: Visibility::Gated,
        capability_ids: &["computer.control"],
    },
    ArticleSeed {
        id: "computer-use.isolated-guest",
        title: "Isolated guest Computer Use",
        topic: Topic::ComputerUse,
        summary: "Understand the isolated guest boundary without treating source proof as a usable VM.",
        body: "An isolated guest is a planned separate visual surface for bounded Computer Use, and it is not qualified for use in this release. The helper and guest image still need review and signing, one agent lease must control a guest at a time, frames must be redacted, and host clipboard, shares, raw global input, and guest networking remain denied. Source-level lease and projection tests do not prove a packaged VM, a guest boot, rendered frames, or host input.",
        aliases: &[
            "vm computer use",
            "virtual machine screen",
            "sandboxed desktop",
            "guest computer",
        ],
        keywords: &[
            "guest",
            "vm",
            "isolated",
            "helper",
            "lease",
            "frame",
            "redaction",
        ],
        source_ids: &["computer-use.blockers", "computer-use.trust"],
        visibility: Visibility::Gated,
        capability_ids: &["computer.observe"],
    },
    ArticleSeed {
        id: "computer-use.coordination",
        title: "Coordinate multiple Computer Use agents",
        topic: Topic::ComputerUse,
        summary: "Keep simultaneous agents from fighting over the same visual surface.",
        body: "Coordination is lease-based: an agent must hold the exact guest or session authority and revision before it can act. A second agent, a stale observation, the wrong session, Stop, or Take over must be denied without mutation. Separate guests or explicitly disjoint scopes are required for parallel work.",
        aliases: &[
            "two agents one screen",
            "multiple agents",
            "agent contention",
            "coordinate computer agents",
        ],
        keywords: &[
            "multi-agent",
            "coordination",
            "lease",
            "revision",
            "stale",
            "contention",
        ],
        source_ids: &["computer-use.evidence"],
        visibility: Visibility::Operator,
        capability_ids: &["computer.control"],
    },
    ArticleSeed {
        id: "operations.durable-recovery",
        title: "Recover a durable run safely",
        topic: Topic::Operations,
        summary: "Resume from an explicit checkpoint without guessing whether a send happened.",
        body: "Durable runs expose a state, a cursor, and an evidence trail that survive an app restart. Reconnect from the advertised cursor, treat uncertain delivery as unknown, and use an explicit retry or continuation action. A restart is not permission to resend. Never infer that a linked session or a visible queue means a provider request was sent.",
        aliases: &[
            "restart a run",
            "recover interrupted agent",
            "resume after crash",
            "unknown send",
            "duplicate send",
        ],
        keywords: &[
            "durable",
            "restart",
            "recover",
            "checkpoint",
            "cursor",
            "retry",
            "uncertain",
        ],
        source_ids: &["durable.lifecycle", "durable.bounds"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "operations.evidence",
        title: "Read progress and evidence correctly",
        topic: Topic::Operations,
        summary: "Separate deterministic tests, live-provider evidence, hardware proof, and soak reports.",
        body: "A passing unit test proves an in-tree behavior on a named revision. It does not prove a live provider campaign, a packaged macOS identity, a multi-day operational soak, or a VM guest. Always read the exact revision, the evidence kind, the remaining gate, and whether the result is candidate-only.",
        aliases: &[
            "is this certified",
            "what does pass mean",
            "qualification",
            "proof",
            "release gate",
        ],
        keywords: &[
            "evidence",
            "test",
            "live",
            "soak",
            "certified",
            "qualification",
            "release",
        ],
        source_ids: &["verification.paths"],
        visibility: Visibility::Public,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "operations.verification-limits",
        title: "Know which verification commands are supported",
        topic: Topic::Operations,
        summary: "Some whole-workspace commands are explicitly unsupported and prove nothing.",
        body: "Run the supported per-package paths that CI runs. A root-wide workspace test invocation is unsupported here and a failure from it is not evidence about the code under review. Read the supported-paths list before quoting a command result as a gate.",
        aliases: &[
            "cargo test workspace",
            "which tests to run",
            "ci commands",
            "unsupported command",
        ],
        keywords: &[
            "verification",
            "cargo",
            "workspace",
            "unsupported",
            "ci",
            "gate",
        ],
        source_ids: &["verification.unsupported", "verification.paths"],
        visibility: Visibility::Gated,
        capability_ids: &[],
    },
    ArticleSeed {
        id: "operations.queue-and-steer",
        title: "Queue and steer work without losing scope",
        topic: Topic::Operations,
        summary: "Queue, steer, or cancel a run with explicit request ids and the same fences.",
        body: "Queue and steer are separate bounded operations, not hidden prompt injection. Use a fresh idempotency key for each intent, preserve the run and workspace identity, and reconcile the queue revision before editing or removing an entry. A retry after an uncertain response is allowed only when the durable oracle proves the original request was not accepted.",
        aliases: &[
            "prompt queue",
            "steer agent",
            "send next prompt",
            "cancel a run",
            "deferred steering",
        ],
        keywords: &[
            "queue",
            "steer",
            "idempotency",
            "revision",
            "retry",
            "scope",
        ],
        source_ids: &["mcp.coordinator", "durable.lifecycle"],
        visibility: Visibility::Gated,
        capability_ids: &["run.queue"],
    },
    ArticleSeed {
        id: "operations.retention",
        title: "Understand durable retention and replay windows",
        topic: Topic::Operations,
        summary: "Retention decides how far back a reconnecting client may resume.",
        body: "The coordinator retains a bounded event window per session. A cursor older than the retained window cannot be resumed and must be reported as a recovery condition rather than silently restarted from zero. Retention limits are an operational setting and are visible to operators only.",
        aliases: &[
            "replay window",
            "event retention",
            "cursor expired",
            "how far back",
        ],
        keywords: &[
            "retention",
            "replay",
            "cursor",
            "window",
            "recovery",
            "coordinator",
        ],
        source_ids: &["mcp.retention"],
        visibility: Visibility::Operator,
        capability_ids: &["run.review"],
    },
];
