import { describe, expect, it } from "vitest";

import v1Fixture from "./__fixtures__/progress-projection.v1.json";
import v2Fixture from "./__fixtures__/progress-projection.v2.json";
import {
  isRedactedProgressProjection,
  PROGRESS_PROJECTION_SCHEMA_VERSION,
  type AnyRunProgressProjection,
  type RunStopDetail,
  type RunStopTool,
} from "./protocol";

/**
 * These fixtures are generated by the Rust test `wire_fixtures_match_rust_serialization`
 * and committed, so this suite reads the same bytes the host emits rather than a
 * hand-written guess at them. A shape change on either side fails one of the two.
 */
describe("progress projection wire compatibility", () => {
  it("narrows the current shape and exposes the stop detail", () => {
    const projection = v2Fixture as unknown as AnyRunProgressProjection;
    expect(isRedactedProgressProjection(projection)).toBe(true);
    if (!isRedactedProgressProjection(projection)) throw new Error("unreachable");

    expect(projection.schemaVersion).toBe(PROGRESS_PROJECTION_SCHEMA_VERSION);
    const detail = projection.stopDetail as RunStopDetail;
    expect(detail.kind).toBe("inert_repeat");
    expect(detail.repeats).toBe(4);
    expect(detail.tool satisfies RunStopTool | null | undefined).toBe("task_output");
  });

  it("carries no prompt text in the current shape", () => {
    const raw = JSON.stringify(v2Fixture);
    expect(raw).not.toContain("promptPreview");
    expect(raw).not.toContain("the user's own prompt text");
  });

  it("collapses an unresolved tool to the fixed category, not the original name", () => {
    const raw = JSON.stringify(v2Fixture);
    // The fixture deliberately includes an MCP-style name resolved by the host.
    expect(raw).toContain('"tool":"unresolved"');
    expect(raw).not.toContain("mcp__");
  });

  it("does not mistake the historical shape for a redacted one", () => {
    const legacy = v1Fixture as unknown as AnyRunProgressProjection;
    expect(isRedactedProgressProjection(legacy)).toBe(false);
    // A v1 payload still carries the prompt, which is exactly why it must not
    // be narrowed to the redacted type.
    expect(JSON.stringify(legacy)).toContain("promptPreview");
  });

  it("treats a payload with no schemaVersion as v1", () => {
    const versionless = { runId: "r", sessionId: "s" } as unknown as AnyRunProgressProjection;
    expect(isRedactedProgressProjection(versionless)).toBe(false);
  });

  it("accepts a future shape as at least redacted", () => {
    const future = { schemaVersion: 99 } as unknown as AnyRunProgressProjection;
    expect(isRedactedProgressProjection(future)).toBe(true);
  });
});
